### ISSUE TITLE
Support application of onnx and pmml models

### ISSUE THREAD

**Issue by MaxNoe** [fact-project/aict-tools#103]
We should also be able to apply stored models in pmml and onnx format

**Comment by LukasNickel** [comment]
This enables us to load more generic models, right? Like pytorch,...? 
More open formats sounds better than less!

**Comment by MaxNoe** [comment]
In theory yes, but for starters it enables us to use the models we store as pmml or onnx ourselves.

**Comment by LukasNickel** [comment]
So we export trained models in these formats as well?

**Comment by MaxNoe** [comment]
Yes, it's possible to store models in pmml since basically forever and onnx since #85

**Comment by LukasNickel** [comment]
Oh, thats nice!
