### ISSUE TITLE
Reading CTA dl1 files does not work without specifying columns

### ISSUE THREAD

**Issue by LukasNickel** [fact-project/aict-tools#153]

**Comment by maxnoe** [comment]
You mean features in the config? That's expected. Training a model without features doesn't make sense. Just choosing all available also doesn't really make sense. People need to make a choice here.

So probably we can just improve the error message? `"features" is a required configuration field"` ?

**Comment by maxnoe** [comment]
Currently this just raises a `KeyError`. Which is also pretty clear I'd say.

**Comment by LukasNickel** [comment]
To elaborate:
It is not a problem for the scripts, the methods just dont behave the same way. I can do `from aict_tools.io import read_data` to use that method in external scripts or when looking at FACT data when I do not necessarily know what columns are present.
Just handy sometimes. 
But for CTA files I need to use `read_telescope_data` anyway, which requires to set up an `AICTConfig` anyway (which I forgot), so thats probably not a use case right now
