### ISSUE TITLE
x axis unit label in Bias and Resolution plot doesn't fit

### ISSUE THREAD

**Issue by Hckjs** [fact-project/aict-tools#159]
https://github.com/fact-project/aict-tools/blob/0298fb588800655c1aafd1a5707d63b2815248ac/aict_tools/plotting.py#L112-L115

Since the x-axis is log-scaled, the unit in the label should just be E_{MC}/TeV

**Comment by maxnoe** [comment]
@Hckjs yep, you're right. Could you open a PR with the fix?

**Comment by maxnoe** [comment]
And while you are at it, maybe change it to `E_{{\mathrm{{true}}}`?
